version: "3.3"

services:

  dashmachine:
    image: rmountjoy/dashmachine:v0.5-4
    container_name: dashmachine
    volumes:
      - ./app_data:/dashmachine/dashmachine/user_data
    ports:
      - "8200:5000"
    restart: unless-stopped

    
