version: "3.3"

services:

  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    volumes:
      - ./DashMachine:/dashmachine/dashmachine/user_data
    ports:
      - 8200:5000
    restart: unless-stopped

    